/**
 * Brazilian Portuguese (pt-BR) localization for Better Auth UI
 *
 * This is a complete set of translations. You can expand this by checking
 * the AuthLocalization type from @daveyplate/better-auth-ui for all available keys.
 *
 * To use: Add `localization={ptBR}` to your AuthUIProvider
 */
export const ptBR = {
  // ============================================================================
  // AUTHENTICATION VIEWS
  // ============================================================================
  ACCEPT_INVITATION: "Aceitar Convite",
  ACCEPT_INVITATION_DESCRIPTION: "Você foi convidado para se juntar a uma organização.",
  ALREADY_HAVE_AN_ACCOUNT: "Já tem uma conta?",
  DISABLED_CREDENTIALS_DESCRIPTION: "Escolha um provedor para fazer login em sua conta",
  DONT_HAVE_AN_ACCOUNT: "Não tem uma conta?",
  FORGOT_PASSWORD: "Esqueci a Senha",
  FORGOT_PASSWORD_DESCRIPTION: "Recupere o acesso à sua conta",
  MAGIC_LINK: "Link Mágico",
  MAGIC_LINK_DESCRIPTION: "Entre sem senha por e-mail",
  RECOVER_ACCOUNT: "Recuperar Conta",
  RECOVER_ACCOUNT_DESCRIPTION: "Digite um código de backup para acessar sua conta",
  RESET_PASSWORD: "Redefinir Senha",
  RESET_PASSWORD_DESCRIPTION: "Crie uma nova senha",
  SET_PASSWORD_DESCRIPTION: "Clique no botão abaixo para receber um e-mail para configurar uma senha para sua conta.",
  SIGN_IN: "Entrar",
  SIGN_IN_DESCRIPTION: "Entre com sua conta",
  SIGN_IN_USERNAME_DESCRIPTION: "Digite seu nome de usuário ou e-mail abaixo para fazer login em sua conta",
  SIGN_UP: "Criar Conta",
  SIGN_UP_DESCRIPTION: "Crie sua nova conta",
  SIGN_OUT: "Sair",
  VERIFY_YOUR_EMAIL: "Verifique Seu E-mail",
  VERIFY_YOUR_EMAIL_DESCRIPTION: "Verifique seu endereço de e-mail. Verifique sua caixa de entrada para o e-mail de verificação. Se não recebeu o e-mail, clique no botão abaixo para reenviar.",

  // ============================================================================
  // FORM FIELDS & VALIDATION
  // ============================================================================
  BACKUP_CODE_PLACEHOLDER: "Código de Backup",
  BACKUP_CODE_REQUIRED: "Código de backup é obrigatório",
  CONFIRM_PASSWORD: "Confirmar Senha",
  CONFIRM_PASSWORD_PLACEHOLDER: "Confirmar Senha",
  CONFIRM_PASSWORD_REQUIRED: "Confirmação de senha é obrigatória",
  CURRENT_PASSWORD: "Senha Atual",
  CURRENT_PASSWORD_PLACEHOLDER: "Senha Atual",
  EMAIL: "E-mail",
  EMAIL_DESCRIPTION: "Digite o endereço de e-mail que deseja usar para fazer login.",
  EMAIL_INSTRUCTIONS: "Digite um endereço de e-mail válido.",
  EMAIL_IS_THE_SAME: "O e-mail é o mesmo",
  EMAIL_PLACEHOLDER: "seu@email.com",
  EMAIL_REQUIRED: "Endereço de e-mail é obrigatório",
  EMAIL_VERIFY_CHANGE: "Verifique seu e-mail para confirmar a alteração.",
  EMAIL_VERIFICATION: "Verifique seu e-mail para o link de verificação.",
  MEMBER_EMAIL: "E-mail do Membro",
  MEMBER_EMAIL_PLACEHOLDER: "email@exemplo.com",
  NAME: "Nome",
  NAME_DESCRIPTION: "Digite seu nome completo ou um nome de exibição.",
  NAME_INSTRUCTIONS: "Use no máximo 32 caracteres.",
  NAME_PLACEHOLDER: "Seu nome completo",
  NEW_PASSWORD: "Nova Senha",
  NEW_PASSWORD_PLACEHOLDER: "Nova Senha",
  NEW_PASSWORD_REQUIRED: "Nova senha é obrigatória",
  ONE_TIME_PASSWORD: "Senha de Uso Único",
  ORGANIZATION_NAME: "Nome da Organização",
  ORGANIZATION_NAME_DESCRIPTION: "Este é o nome visível da sua organização.",
  ORGANIZATION_NAME_INSTRUCTIONS: "Use no máximo 32 caracteres.",
  ORGANIZATION_NAME_PLACEHOLDER: "Nome da sua organização",
  ORGANIZATION_SLUG: "URL da Organização",
  ORGANIZATION_SLUG_DESCRIPTION: "Este é o namespace de URL da sua organização.",
  ORGANIZATION_SLUG_INSTRUCTIONS: "Use no máximo 48 caracteres.",
  ORGANIZATION_SLUG_PLACEHOLDER: "url-da-organizacao",
  PASSWORD: "Senha",
  PASSWORD_PLACEHOLDER: "Digite sua senha",
  PASSWORD_REQUIRED: "Senha é obrigatória",
  PASSWORDS_DO_NOT_MATCH: "As senhas não coincidem",
  SIGN_IN_USERNAME_PLACEHOLDER: "Nome de usuário ou e-mail",
  TWO_FACTOR_CODE: "Código de Verificação",
  TWO_FACTOR_CODE_PLACEHOLDER: "000000",
  USERNAME: "Nome de Usuário",
  USERNAME_DESCRIPTION: "Digite o nome de usuário que deseja usar para fazer login.",
  USERNAME_INSTRUCTIONS: "Use no máximo 32 caracteres.",
  USERNAME_PLACEHOLDER: "Nome de Usuário",

  // ============================================================================
  // ACTIONS & BUTTONS
  // ============================================================================
  ACCEPT: "Aceitar",
  ADD: "Adicionar",
  ADD_ACCOUNT: "Adicionar Conta",
  ADD_PASSKEY: "Adicionar Chave de Acesso",
  CANCEL: "Cancelar",
  CANCEL_INVITATION: "Cancelar Convite",
  CHANGE_PASSWORD: "Alterar Senha",
  CLOSE: "Fechar",
  CONFIRM_DELETE: "Confirmar Exclusão",
  CONNECT: "Conectar",
  CONTINUE: "Continuar",
  CONTINUE_WITH_AUTHENTICATOR: "Continuar com Autenticador",
  COPY: "Copiar",
  COPY_ALL_CODES: "Copiar todos os códigos",
  COPY_TO_CLIPBOARD: "Copiar para a área de transferência",
  CREATE_API_KEY: "Criar Chave de API",
  CREATE_ORGANIZATION: "Criar Organização",
  DELETE: "Excluir",
  DELETE_API_KEY: "Excluir Chave",
  DELETE_AVATAR: "Remover Foto",
  DELETE_LOGO: "Excluir Logo",
  DELETE_ORGANIZATION: "Excluir Organização",
  DISABLE_TWO_FACTOR: "Desativar 2FA",
  DISCONNECT: "Desconectar",
  DONE: "Concluído",
  DOWNLOAD: "Baixar",
  EDIT: "Editar",
  ENABLE_TWO_FACTOR: "Ativar 2FA",
  FILTER: "Filtrar",
  FORGOT_AUTHENTICATOR: "Esqueceu o autenticador?",
  FORGOT_PASSWORD_ACTION: "Enviar link de redefinição",
  FORGOT_PASSWORD_LINK: "Esqueceu sua senha?",
  GO_BACK: "Voltar",
  INVITE_MEMBER: "Convidar Membro",
  LEAVE_ORGANIZATION: "Sair da Organização",
  LINK: "Vincular",
  MAGIC_LINK_ACTION: "Enviar link mágico",
  MANAGE: "Gerenciar",
  MANAGE_ORGANIZATION: "Gerenciar Organização",
  RECOVER_ACCOUNT_ACTION: "Recuperar conta",
  REJECT: "Recusar",
  REMEMBER_ME: "Lembrar-me",
  REMOVE: "Remover",
  REMOVE_AVATAR: "Remover Foto",
  REMOVE_MEMBER: "Remover Membro",
  RESEND_CODE: "Reenviar código",
  RESEND_VERIFICATION_EMAIL: "Reenviar e-mail de verificação",
  RESET_PASSWORD_ACTION: "Salvar nova senha",
  REVOKE: "Revogar",
  REVOKE_SESSION: "Encerrar Sessão",
  SAVE: "Salvar",
  SEARCH: "Pesquisar",
  SELECT_ROLE: "Selecionar uma função",
  SEND_INVITATION: "Enviar Convite",
  SEND_VERIFICATION_CODE: "Enviar código de verificação",
  SIGN_IN_ACTION: "Entrar",
  SIGN_IN_WITH: "Entrar com",
  SIGN_UP_ACTION: "Criar uma conta",
  SORT: "Ordenar",
  SWITCH_ACCOUNT: "Trocar Conta",
  SWITCH_ORGANIZATION: "Trocar Organização",
  TRUST_DEVICE: "Confiar neste dispositivo",
  TWO_FACTOR_ACTION: "Verificar código",
  UNLINK: "Desvincular",
  UPDATE_AVATAR: "Atualizar Foto",
  UPDATE_LOGO: "Enviar Logo",
  UPDATE_MEMBER_ROLE: "Atualizar Função",
  UPDATE_ROLE: "Atualizar Função",
  UPLOAD: "Enviar",
  UPLOAD_AVATAR: "Enviar Avatar",
  VERIFY_CODE: "Verificar Código",
  VIEW: "Visualizar",

  // ============================================================================
  // SUCCESS MESSAGES
  // ============================================================================
  API_KEY_CREATED: "Chave de API criada com sucesso!",
  CHANGE_PASSWORD_SUCCESS: "Sua senha foi alterada.",
  CREATE_API_KEY_SUCCESS: "Copie sua chave de API e armazene-a em um local seguro. Por razões de segurança, não podemos mostrá-la novamente.",
  CREATE_ORGANIZATION_SUCCESS: "Organização criada com sucesso",
  COPIED: "Copiado!",
  DELETE_ACCOUNT_SUCCESS: "Sua conta foi excluída permanentemente.",
  FORGOT_PASSWORD_EMAIL: "Verifique seu e-mail para redefinir sua senha.",
  INVITATION_ACCEPTED: "Convite aceito com sucesso",
  INVITATION_CANCELLED: "Convite cancelado com sucesso",
  INVITATION_REJECTED: "Convite rejeitado com sucesso",
  LEAVE_ORGANIZATION_SUCCESS: "Você saiu da organização com sucesso.",
  MAGIC_LINK_EMAIL: "Verifique seu e-mail para o link de acesso!",
  MEMBER_ROLE_UPDATED: "Função do membro atualizada com sucesso",
  REMOVE_MEMBER_SUCCESS: "Membro removido com sucesso",
  RESET_PASSWORD_SUCCESS: "Sua senha foi redefinida com sucesso!",
  SAVED: "Salvo!",
  SEND_INVITATION_SUCCESS: "Convite enviado com sucesso",
  SIGN_UP_EMAIL: "Verifique seu e-mail para o link de verificação.",
  TWO_FACTOR_ENABLED: "2FA Ativado",
  UPDATED_SUCCESSFULLY: "Atualizado com sucesso",

  // ============================================================================
  // SETTINGS & ACCOUNT MANAGEMENT
  // ============================================================================
  ACCOUNT: "Conta",
  ACCOUNT_SETTINGS: "Configurações da Conta",
  ACCOUNT_SETTINGS_DESCRIPTION: "Gerencie suas informações pessoais e preferências.",
  ACCOUNTS: "Contas",
  ACCOUNTS_DESCRIPTION: "Alterne entre suas contas atualmente conectadas.",
  ACCOUNTS_INSTRUCTIONS: "Entre em uma conta adicional.",
  APP: "Aplicativo",
  AVATAR: "Foto de Perfil",
  AVATAR_DESCRIPTION: "Atualize sua foto de perfil.",
  AVATAR_INSTRUCTIONS: "Um avatar é opcional, mas fortemente recomendado.",
  LOGO: "Logo",
  LOGO_DESCRIPTION: "Clique no logo para enviar um personalizado dos seus arquivos.",
  LOGO_INSTRUCTIONS: "Um logo é opcional, mas fortemente recomendado.",
  ORGANIZATION_LOGO: "Logo da Organização",
  PERSONAL_ACCOUNT: "Conta Pessoal",
  PROVIDERS: "Contas Vinculadas",
  PROVIDERS_DESCRIPTION: "Gerencie suas contas de redes sociais vinculadas.",
  SECURITY: "Segurança",
  SECURITY_SETTINGS: "Configurações de Segurança",
  SECURITY_SETTINGS_DESCRIPTION: "Gerencie suas configurações de segurança e privacidade.",
  SETTINGS: "Configurações",
  SETTINGS_DESCRIPTION: "Gerencie as configurações da sua conta.",
  USER: "Usuário",

  // ============================================================================
  // SECURITY FEATURES
  // ============================================================================
  ACTIVE_SESSIONS: "Sessões Ativas",
  BACKUP_CODES: "Códigos de Backup",
  BACKUP_CODES_DESCRIPTION: "Guarde estes códigos em um local seguro. Você pode usá-los para acessar sua conta se perder o acesso ao seu dispositivo de autenticação.",
  CURRENT_SESSION: "Esta Sessão",
  LAST_ACTIVE: "Última atividade",
  PASSKEY: "Chave de Acesso",
  PASSKEYS: "Chaves de Acesso",
  PASSKEYS_DESCRIPTION: "Gerencie suas chaves de acesso para acesso seguro.",
  PASSKEYS_INSTRUCTIONS: "Acesse sua conta com segurança sem senha.",
  SESSIONS: "Sessões Ativas",
  SESSIONS_DESCRIPTION: "Gerencie suas sessões ativas em diferentes dispositivos.",
  SESSION_NOT_FRESH: "Sua sessão não está atualizada. Faça login novamente.",
  TWO_FACTOR: "Autenticação de Dois Fatores",
  TWO_FACTOR_CARD_DESCRIPTION: "Adicione uma camada extra de segurança à sua conta.",
  TWO_FACTOR_DESCRIPTION: "Adicione uma camada extra de segurança à sua conta.",
  TWO_FACTOR_DISABLED: "2FA Desativado",
  TWO_FACTOR_DISABLE_INSTRUCTIONS: "Digite sua senha para desativar 2FA.",
  TWO_FACTOR_ENABLE_INSTRUCTIONS: "Digite sua senha para ativar 2FA.",
  TWO_FACTOR_PROMPT: "Autenticação de Dois Fatores",
  TWO_FACTOR_TOTP_LABEL: "Escaneie o Código QR com seu Autenticador",

  // ============================================================================
  // ORGANIZATIONS
  // ============================================================================
  CREATE_ORGANIZATION_DESCRIPTION: "Crie uma organização para colaborar com outros usuários.",
  DELETE_ORGANIZATION_DESCRIPTION: "Exclua permanentemente esta organização e todos os seus dados.",
  DELETE_ORGANIZATION_INSTRUCTIONS: "Digite o slug da organização para continuar:",
  NO_ORGANIZATIONS: "Você ainda não tem nenhuma organização.",
  ORGANIZATION: "Organização",
  ORGANIZATIONS: "Organizações",
  ORGANIZATIONS_DESCRIPTION: "Gerencie suas organizações e participações.",
  ORGANIZATIONS_INSTRUCTIONS: "Crie uma organização para colaborar com outros usuários.",
  SLUG_DOES_NOT_MATCH: "O slug não corresponde",
  SLUG_REQUIRED: "Slug da organização é obrigatório",

  // ============================================================================
  // MEMBERS & INVITATIONS
  // ============================================================================
  ADMIN: "Administrador",
  GUEST: "Convidado",
  INVITE_MEMBER_DESCRIPTION: "Convide outras pessoas para se juntarem à sua organização.",
  LEAVE_ORGANIZATION_CONFIRM: "Tem certeza de que deseja sair desta organização?",
  MEMBER: "Membro",
  MEMBERS: "Membros",
  MEMBERS_DESCRIPTION: "Gerencie os membros e convites da sua organização.",
  MEMBERS_INSTRUCTIONS: "Convide novos membros para sua organização.",
  OWNER: "Proprietário",
  PENDING_INVITATIONS: "Convites Pendentes",
  PENDING_INVITATIONS_DESCRIPTION: "Gerencie convites pendentes para sua organização.",
  PENDING_USER_INVITATIONS_DESCRIPTION: "Convites que você recebeu de organizações.",
  REMOVE_MEMBER_CONFIRM: "Tem certeza de que deseja remover este membro da organização?",
  ROLE: "Função",
  UPDATE_ROLE_DESCRIPTION: "Atualize a função deste membro",

  // ============================================================================
  // API KEYS
  // ============================================================================
  API_KEY_DELETED: "Chave de API excluída com sucesso!",
  API_KEY_NAME: "Nome da Chave",
  API_KEY_NAME_PLACEHOLDER: "Nome descritivo para a chave",
  API_KEYS: "Chaves de API",
  API_KEYS_DESCRIPTION: "Gerencie suas chaves de API para integração com outros sistemas.",
  API_KEYS_INSTRUCTIONS: "Gere chaves de API para acessar sua conta programaticamente.",
  CONFIRM_DELETE_API_KEY: "Tem certeza de que deseja excluir esta chave de API?",
  CREATE_API_KEY_DESCRIPTION: "Digite um nome único para sua chave de API para diferenciá-la de outras chaves.",
  EXPIRES: "Expira",
  EXPIRES_ON: "Expira em",
  NEVER_EXPIRES: "Nunca expira",
  NO_EXPIRATION: "Sem Expiração",

  // ============================================================================
  // COMMON UI ELEMENTS
  // ============================================================================
  BY_CONTINUING_YOU_AGREE: "Ao continuar, você concorda com",
  DETAILS: "Detalhes",
  DESCRIPTION: "Descrição",
  LOADING: "Carregando...",
  NO: "Não",
  OPTIONAL: "Opcional",
  OR: "OU",
  OR_CONTINUE_WITH: "Ou continue com",
  PRIVACY_POLICY: "Política de Privacidade",
  PROTECTED_BY_RECAPTCHA: "Este site é protegido por reCAPTCHA.",
  REQUIRED: "Obrigatório",
  TERMS_OF_SERVICE: "Termos de Serviço",
  UNKNOWN: "Desconhecido",
  YES: "Sim",

  // ============================================================================
  // ERROR MESSAGES & VALIDATION
  // ============================================================================
  DELETE_ACCOUNT: "Excluir Conta",
  DELETE_ACCOUNT_CONFIRMATION: "Tem certeza de que deseja excluir sua conta? Esta ação não pode ser desfeita.",
  DELETE_ACCOUNT_DESCRIPTION: "Exclua permanentemente sua conta e todos os seus dados.",
  DELETE_ACCOUNT_NOT_FRESH: "Faça logout e login novamente para excluir sua conta.",
  IS_INVALID: "é inválido",
  IS_REQUIRED: "é obrigatório",
  IS_THE_SAME: "é o mesmo",
  REQUEST_FAILED: "Falha na solicitação",
} as const;
